-- GOOGLE SERP RANK TRACKER (SearchAPI.io)
-- Aman dijalankan ulang. Jika sebelumnya sudah menjalankan schema versi Search Console,
-- file ini akan menambahkan kolom yang dibutuhkan tanpa menghapus histori lama.

create table if not exists public.rank_history (
  id bigint generated by default as identity primary key,
  query text not null,
  domain text not null,
  device text not null default 'MOBILE',
  country text not null default 'ID',
  data_hour timestamptz not null,
  position double precision,
  clicks integer not null default 0,
  impressions integer not null default 0,
  ctr double precision not null default 0,
  is_partial boolean not null default false,
  synced_at timestamptz not null default now(),
  unique (query, domain, device, country, data_hour)
);

-- Versi lama mewajibkan position. SERP bisa "tidak ditemukan", jadi harus boleh NULL.
alter table public.rank_history alter column position drop not null;
alter table public.rank_history add column if not exists found boolean;
alter table public.rank_history add column if not exists result_url text;
alter table public.rank_history add column if not exists result_title text;
alter table public.rank_history add column if not exists results_checked integer;
alter table public.rank_history add column if not exists provider text;

create index if not exists rank_history_lookup_idx
  on public.rank_history (query, domain, device, country, data_hour desc);

create table if not exists public.rank_status (
  query text not null,
  domain text not null,
  device text not null default 'MOBILE',
  country text not null default 'ID',
  status text not null default 'waiting',
  last_checked_at timestamptz,
  last_data_hour timestamptz,
  last_position double precision,
  message text,
  primary key (query, domain, device, country)
);

alter table public.rank_status add column if not exists found boolean;
alter table public.rank_status add column if not exists last_result_url text;
alter table public.rank_status add column if not exists last_result_title text;
alter table public.rank_status add column if not exists results_checked integer;
alter table public.rank_status add column if not exists provider text;

alter table public.rank_history enable row level security;
alter table public.rank_status enable row level security;

-- Tidak ada policy publik. Browser membaca data melalui /api/data.
