-- Jalankan seluruh file ini di Supabase -> SQL Editor.

create table if not exists public.rank_history (
  id bigint generated by default as identity primary key,
  query text not null,
  domain text not null,
  device text not null default 'ALL',
  country text not null default 'ALL',
  data_hour timestamptz not null,
  position double precision not null,
  clicks integer not null default 0,
  impressions integer not null default 0,
  ctr double precision not null default 0,
  is_partial boolean not null default false,
  synced_at timestamptz not null default now(),
  unique (query, domain, device, country, data_hour)
);

create index if not exists rank_history_lookup_idx
  on public.rank_history (query, domain, device, country, data_hour desc);

create table if not exists public.rank_status (
  query text not null,
  domain text not null,
  device text not null default 'ALL',
  country text not null default 'ALL',
  status text not null default 'waiting',
  last_checked_at timestamptz,
  last_data_hour timestamptz,
  last_position double precision,
  message text,
  primary key (query, domain, device, country)
);

-- Backend Vercel memakai secret/service-role key, jadi tabel tidak perlu dibuka ke browser.
alter table public.rank_history enable row level security;
alter table public.rank_status enable row level security;

-- Tidak membuat policy publik. Semua akses dari browser lewat /api/data.
